### ISSUE TITLE
`kopylot --version` should not require the token to be set

### ISSUE THREAD

**Issue by petervandenabeele** [avsthiago/kopylot#9]
As far as I am aware, most programs can run `<program> --version` without external dependencies or actual secrets/tokens present.

This fails for me on the current version (0.0.4):

```
➜  kopylot git:(main) kopylot --version
Error: KOPYLOT_AUTH_TOKEN not set.
```

**Comment by avsthiago** [comment]
I just merged a fix for that. Thanks for reporting the 🐛 !
